---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grafana
  name: grafana
spec:
  containers:
  - image: grafana/grafana:8.4.4
    name: grafana
    ports:
      - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}