apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: homeassistant
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: homeassistant
spec:
  type: NodePort
  selector:
    matchLabels:
      run: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grafana
  name: grafana
  namespace: homeassistant
spec:
  containers:
  - image: grafana/grafana:8.4.4
    name: grafana
    ports:
      - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}