apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: homeassistant
  name: homeassistant
spec:
  containers:
  - image: ghcr.io/home-assistant/home-assistant:stable
    name: homeassistant
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
