apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: influxdb
  name: influxdb
spec:
  containers:
  - image: influxdb:1.8.10
    name: influxdb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
