apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mariadb
  name: mariadb
spec:
  containers:
  - image: mariadb:10.7
    name: mariadb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
