apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pihole
  name: pihole
spec:
  containers:
  - image: pihole/pihole:2022.02.1
    name: pihole
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
